version: '2'
services:
  jenkins:
    build: ./jenkins
    image: jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - app-data:/deploy
    ports:
      - 8080:8080
    networks:
      - mynetwork
  django:
    build: ./rp-portafolio
    image: django
    container_name: django
    volumes:
      - app-data:/app
    ports:
      - 8000:8000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  jenkins-data:
  app-data:
  