version: '2'
services:
  jenkins:
    build: ./jenkins
    image: jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  jenkins-data:
  